// Generated by scripts/generate-material-comparison.js — do not edit by hand.

export type MaterialComparisonRow = {
  attribute: string;
  values: Record<string, string>;
};

export const MATERIAL_COMPARISON_ATTRIBUTE_LABEL = "Material";

export const MATERIAL_COMPARISON_COLUMNS = [
  "Flex Trim",
  "Zzz Flex",
  "Ultra-Flex",
  "Machinable S4S",
  "Ultra-Fire Flex"
] as const;

export const MATERIAL_COMPARISON_ROWS: MaterialComparisonRow[] = [
  {
    "attribute": "Flexibility",
    "values": {
      "Flex Trim": "OO",
      "Zzz Flex": "OOO",
      "Ultra-Flex": "O",
      "Machinable S4S": "O",
      "Ultra-Fire Flex": "OO"
    }
  },
  {
    "attribute": "Paintability",
    "values": {
      "Flex Trim": "OOO",
      "Zzz Flex": "OOO",
      "Ultra-Flex": "OOO",
      "Machinable S4S": "OOO",
      "Ultra-Fire Flex": "OOO"
    }
  },
  {
    "attribute": "Stainability",
    "values": {
      "Flex Trim": "OO",
      "Zzz Flex": "OO",
      "Ultra-Flex": "OOO",
      "Machinable S4S": "N/A",
      "Ultra-Fire Flex": "O"
    }
  },
  {
    "attribute": "Lightweight",
    "values": {
      "Flex Trim": "O",
      "Zzz Flex": "O",
      "Ultra-Flex": "OOO",
      "Machinable S4S": "OO",
      "Ultra-Fire Flex": "O"
    }
  },
  {
    "attribute": "Machinability",
    "values": {
      "Flex Trim": "O",
      "Zzz Flex": "O",
      "Ultra-Flex": "OO",
      "Machinable S4S": "OOO",
      "Ultra-Fire Flex": "O"
    }
  },
  {
    "attribute": "Moisture resistance",
    "values": {
      "Flex Trim": "OOO",
      "Zzz Flex": "OOO",
      "Ultra-Flex": "OOO",
      "Machinable S4S": "OOO",
      "Ultra-Fire Flex": "OOO"
    }
  },
  {
    "attribute": "Insect resistance",
    "values": {
      "Flex Trim": "OOO",
      "Zzz Flex": "OOO",
      "Ultra-Flex": "OOO",
      "Machinable S4S": "OOO",
      "Ultra-Fire Flex": "OOO"
    }
  },
  {
    "attribute": "Interior",
    "values": {
      "Flex Trim": "OOO",
      "Zzz Flex": "OOO",
      "Ultra-Flex": "OOO",
      "Machinable S4S": "OOO",
      "Ultra-Fire Flex": "OOO"
    }
  },
  {
    "attribute": "Exterior",
    "values": {
      "Flex Trim": "OOO",
      "Zzz Flex": "OOO",
      "Ultra-Flex": "OOO",
      "Machinable S4S": "OOO",
      "Ultra-Fire Flex": "OOO"
    }
  },
  {
    "attribute": "Extended lengths",
    "values": {
      "Flex Trim": "O",
      "Zzz Flex": "O",
      "Ultra-Flex": "N/A",
      "Machinable S4S": "N/A",
      "Ultra-Fire Flex": "N/A"
    }
  },
  {
    "attribute": "Manufacturing location",
    "values": {
      "Flex Trim": "NC & UT",
      "Zzz Flex": "NC & UT",
      "Ultra-Flex": "UT",
      "Machinable S4S": "UT",
      "Ultra-Fire Flex": "UT"
    }
  },
  {
    "attribute": "Warranty",
    "values": {
      "Flex Trim": "Lifetime",
      "Zzz Flex": "Lifetime",
      "Ultra-Flex": "1 Year",
      "Machinable S4S": "1 Year",
      "Ultra-Fire Flex": "Lifetime"
    }
  }
];
