// Generated by scripts/generate-stock-items.js — do not edit by hand.
// Run: node scripts/generate-stock-items.js

export type StockItem = {
  item: string;
  category: string;
  categorySlug: string;
  dimensions: string;
  thickness: number | null;
  width: number | null;
  configs: string[];
  /** When category is Miscellaneous, the text that was in parentheses in the sheet (e.g. "Crown Backer"). */
  miscellaneousLabel: string | null;
};

export type StockItemSection = { label: string; id: string };

export const STOCK_ITEM_SECTIONS: StockItemSection[] = [
  {
    "label": "Back Band",
    "id": "back-band"
  },
  {
    "label": "Base",
    "id": "base"
  },
  {
    "label": "Base Cap",
    "id": "base-cap"
  },
  {
    "label": "Brick Mould",
    "id": "brick-mould"
  },
  {
    "label": "Casing",
    "id": "casing"
  },
  {
    "label": "Chair Rail",
    "id": "chair-rail"
  },
  {
    "label": "Corner & Cove",
    "id": "corner-cove"
  },
  {
    "label": "Crown",
    "id": "crown"
  },
  {
    "label": "Miscellaneous",
    "id": "miscellaneous"
  },
  {
    "label": "Panel Mould",
    "id": "panel-mould"
  },
  {
    "label": "Rake",
    "id": "rake"
  },
  {
    "label": "Shoe & Quarter Round",
    "id": "shoe-quarter-round"
  },
  {
    "label": "Stop",
    "id": "stop"
  }
];

export const STOCK_ITEMS: StockItem[] = [
  {
    "item": "1 IN QTR",
    "category": "Shoe & Quarter Round",
    "categorySlug": "shoe-quarter-round",
    "dimensions": "1\" x 1\"",
    "thickness": 1,
    "width": 1,
    "configs": [
      "12 FT"
    ],
    "miscellaneousLabel": null
  },
  {
    "item": "C42",
    "category": "Panel Mould",
    "categorySlug": "panel-mould",
    "dimensions": "1-1/16\" x 1-5/8\"",
    "thickness": 1.0625,
    "width": 1.625,
    "configs": [
      "12 FT"
    ],
    "miscellaneousLabel": null
  },
  {
    "item": "C136",
    "category": "Chair Rail",
    "categorySlug": "chair-rail",
    "dimensions": "1-1/16\" x 2-1/2\"",
    "thickness": 1.0625,
    "width": 2.5,
    "configs": [
      "12 FT"
    ],
    "miscellaneousLabel": null
  },
  {
    "item": "C281",
    "category": "Back Band",
    "categorySlug": "back-band",
    "dimensions": "1-5/16\" x 1-5/16\" x 7/8\" Rab",
    "thickness": 1.3125,
    "width": 1.3125,
    "configs": [
      "12 FT"
    ],
    "miscellaneousLabel": null
  },
  {
    "item": "CM1",
    "category": "Casing",
    "categorySlug": "casing",
    "dimensions": "1-1/16\" x 3-1/2\"",
    "thickness": 1.0625,
    "width": 3.5,
    "configs": [
      "12 FT",
      "8 FT",
      "6/0",
      "5/0",
      "4/0",
      "3/0",
      "2/6",
      "2/0",
      "12 FT x 48 IN R",
      "8 FT x 48 IN R"
    ],
    "miscellaneousLabel": null
  },
  {
    "item": "CM2",
    "category": "Miscellaneous",
    "categorySlug": "miscellaneous",
    "dimensions": "11/16\" x 2-1/2\"",
    "thickness": 0.6875,
    "width": 2.5,
    "configs": [
      "12 FT"
    ],
    "miscellaneousLabel": "Crown Backer"
  },
  {
    "item": "CM28",
    "category": "Rake",
    "categorySlug": "rake",
    "dimensions": "3/4\" x 3\"",
    "thickness": 0.75,
    "width": 3,
    "configs": [
      "12 FT"
    ],
    "miscellaneousLabel": null
  },
  {
    "item": "CM37",
    "category": "Crown",
    "categorySlug": "crown",
    "dimensions": "11/16\" x 5-1/16\"",
    "thickness": 0.6875,
    "width": 5.0625,
    "configs": [
      "12 FT"
    ],
    "miscellaneousLabel": null
  },
  {
    "item": "CM45",
    "category": "Crown",
    "categorySlug": "crown",
    "dimensions": "9/16\" x 5-1/4\"",
    "thickness": 0.5625,
    "width": 5.25,
    "configs": [
      "12 FT"
    ],
    "miscellaneousLabel": null
  },
  {
    "item": "CM47",
    "category": "Crown",
    "categorySlug": "crown",
    "dimensions": "9/16\" x 4-5/8\"",
    "thickness": 0.5625,
    "width": 4.625,
    "configs": [
      "12 FT"
    ],
    "miscellaneousLabel": null
  },
  {
    "item": "CM49",
    "category": "Crown",
    "categorySlug": "crown",
    "dimensions": "9/16\" x 3-5/8\"",
    "thickness": 0.5625,
    "width": 3.625,
    "configs": [
      "12 FT"
    ],
    "miscellaneousLabel": null
  },
  {
    "item": "CM52",
    "category": "Crown",
    "categorySlug": "crown",
    "dimensions": "9/16\" x 2-3/4\"",
    "thickness": 0.5625,
    "width": 2.75,
    "configs": [
      "12 FT"
    ],
    "miscellaneousLabel": null
  },
  {
    "item": "CM75",
    "category": "Crown",
    "categorySlug": "crown",
    "dimensions": "9/16\" x 1-5/8\"",
    "thickness": 0.5625,
    "width": 1.625,
    "configs": [
      "12 FT"
    ],
    "miscellaneousLabel": null
  },
  {
    "item": "CM93",
    "category": "Corner & Cove",
    "categorySlug": "corner-cove",
    "dimensions": "3/4\" x 3/4\"",
    "thickness": 0.75,
    "width": 0.75,
    "configs": [
      "12 FT"
    ],
    "miscellaneousLabel": null
  },
  {
    "item": "CM100",
    "category": "Corner & Cove",
    "categorySlug": "corner-cove",
    "dimensions": "11/16\" x 11/16\"",
    "thickness": 0.6875,
    "width": 0.6875,
    "configs": [
      "12 FT"
    ],
    "miscellaneousLabel": null
  },
  {
    "item": "CM101",
    "category": "Corner & Cove",
    "categorySlug": "corner-cove",
    "dimensions": "1/2\" x 1/2\"",
    "thickness": 0.5,
    "width": 0.5,
    "configs": [
      "12 FT"
    ],
    "miscellaneousLabel": null
  },
  {
    "item": "CM105",
    "category": "Shoe & Quarter Round",
    "categorySlug": "shoe-quarter-round",
    "dimensions": "3/4\" x 3/4\"",
    "thickness": 0.75,
    "width": 0.75,
    "configs": [
      "12 FT"
    ],
    "miscellaneousLabel": null
  },
  {
    "item": "CM106",
    "category": "Shoe & Quarter Round",
    "categorySlug": "shoe-quarter-round",
    "dimensions": "11/16\" x 11/16\"",
    "thickness": 0.6875,
    "width": 0.6875,
    "configs": [
      "12 FT"
    ],
    "miscellaneousLabel": null
  },
  {
    "item": "CM127",
    "category": "Shoe & Quarter Round",
    "categorySlug": "shoe-quarter-round",
    "dimensions": "7/16\" x 11/16\"",
    "thickness": 0.4375,
    "width": 0.6875,
    "configs": [
      "12 FT"
    ],
    "miscellaneousLabel": null
  },
  {
    "item": "CM131",
    "category": "Shoe & Quarter Round",
    "categorySlug": "shoe-quarter-round",
    "dimensions": "7/16\" x 3/4\"",
    "thickness": 0.4375,
    "width": 0.75,
    "configs": [
      "12 FT"
    ],
    "miscellaneousLabel": null
  },
  {
    "item": "CM137",
    "category": "Panel Mould",
    "categorySlug": "panel-mould",
    "dimensions": "9/16\" x 1-1/4\"",
    "thickness": 0.5625,
    "width": 1.25,
    "configs": [
      "12 FT"
    ],
    "miscellaneousLabel": null
  },
  {
    "item": "CM163",
    "category": "Base Cap",
    "categorySlug": "base-cap",
    "dimensions": "11/16\" x 1-3/8\"",
    "thickness": 0.6875,
    "width": 1.375,
    "configs": [
      "12 FT",
      "10 FT"
    ],
    "miscellaneousLabel": null
  },
  {
    "item": "CM164",
    "category": "Base Cap",
    "categorySlug": "base-cap",
    "dimensions": "11/16\" x 1-1/8\"",
    "thickness": 0.6875,
    "width": 1.125,
    "configs": [
      "12 FT"
    ],
    "miscellaneousLabel": null
  },
  {
    "item": "CM166",
    "category": "Base Cap",
    "categorySlug": "base-cap",
    "dimensions": "11/16\" x 1-1/4\"",
    "thickness": 0.6875,
    "width": 1.25,
    "configs": [
      "12 FT"
    ],
    "miscellaneousLabel": null
  },
  {
    "item": "CM167",
    "category": "Base Cap",
    "categorySlug": "base-cap",
    "dimensions": "11/16\" x 1-1/8\"",
    "thickness": 0.6875,
    "width": 1.125,
    "configs": [
      "12 FT"
    ],
    "miscellaneousLabel": null
  },
  {
    "item": "CM180",
    "category": "Brick Mould",
    "categorySlug": "brick-mould",
    "dimensions": "1-1/4\" x 2\"",
    "thickness": 1.25,
    "width": 2,
    "configs": [
      "12 FT",
      "8 FT",
      "6/0",
      "5/0",
      "4/0",
      "3/0",
      "2/6",
      "2/0"
    ],
    "miscellaneousLabel": null
  },
  {
    "item": "CM183",
    "category": "Panel Mould",
    "categorySlug": "panel-mould",
    "dimensions": "9/16\" x 1-1/8\"",
    "thickness": 0.5625,
    "width": 1.125,
    "configs": [
      "12 FT"
    ],
    "miscellaneousLabel": null
  },
  {
    "item": "CM184",
    "category": "Panel Mould",
    "categorySlug": "panel-mould",
    "dimensions": "1/2\" x 1-1/2\"",
    "thickness": 0.5,
    "width": 1.5,
    "configs": [
      "12 FT"
    ],
    "miscellaneousLabel": null
  },
  {
    "item": "CM197",
    "category": "Miscellaneous",
    "categorySlug": "miscellaneous",
    "dimensions": "11/16\" x 1-5/8\"",
    "thickness": 0.6875,
    "width": 1.625,
    "configs": [
      "12 FT"
    ],
    "miscellaneousLabel": "Drip Cap"
  },
  {
    "item": "CM205",
    "category": "Corner & Cove",
    "categorySlug": "corner-cove",
    "dimensions": "1-1/4\" x 1-1/4\"",
    "thickness": 1.25,
    "width": 1.25,
    "configs": [
      "12 FT"
    ],
    "miscellaneousLabel": null
  },
  {
    "item": "CM210",
    "category": "Rake",
    "categorySlug": "rake",
    "dimensions": "1-1/8\" x 1-1/8\"",
    "thickness": 1.125,
    "width": 1.125,
    "configs": [
      "12 FT"
    ],
    "miscellaneousLabel": null
  },
  {
    "item": "CM273",
    "category": "Miscellaneous",
    "categorySlug": "miscellaneous",
    "dimensions": "11/16\" x 1-3/4\"",
    "thickness": 0.6875,
    "width": 1.75,
    "configs": [
      "12 FT"
    ],
    "miscellaneousLabel": "Picture Mould"
  },
  {
    "item": "CM280",
    "category": "Back Band",
    "categorySlug": "back-band",
    "dimensions": "11/16\" x 1-1/16\" x 11/16\" Rab",
    "thickness": 0.6875,
    "width": 1.0625,
    "configs": [
      "12 FT"
    ],
    "miscellaneousLabel": null
  },
  {
    "item": "CM281",
    "category": "Back Band",
    "categorySlug": "back-band",
    "dimensions": "11/16\" x 1-1/8\" x 5/8\" Rab",
    "thickness": 0.6875,
    "width": 1.125,
    "configs": [
      "12 FT"
    ],
    "miscellaneousLabel": null
  },
  {
    "item": "CM297",
    "category": "Chair Rail",
    "categorySlug": "chair-rail",
    "dimensions": "11/16\" x 3\"",
    "thickness": 0.6875,
    "width": 3,
    "configs": [
      "12 FT"
    ],
    "miscellaneousLabel": null
  },
  {
    "item": "CM300",
    "category": "Chair Rail",
    "categorySlug": "chair-rail",
    "dimensions": "1-1/16\" x 3\"",
    "thickness": 1.0625,
    "width": 3,
    "configs": [
      "12 FT"
    ],
    "miscellaneousLabel": null
  },
  {
    "item": "CM302",
    "category": "Chair Rail",
    "categorySlug": "chair-rail",
    "dimensions": "1-1/16\" x 2-3/4\"",
    "thickness": 1.0625,
    "width": 2.75,
    "configs": [
      "12 FT"
    ],
    "miscellaneousLabel": null
  },
  {
    "item": "CM356",
    "category": "Casing",
    "categorySlug": "casing",
    "dimensions": "11/16\" x 2-1/4\"",
    "thickness": 0.6875,
    "width": 2.25,
    "configs": [
      "12 FT",
      "8 FT",
      "6/0",
      "5/0",
      "4/0",
      "3/0",
      "2/6",
      "2/0",
      "12 FT x 48 IN R",
      "8 FT x 48 IN R"
    ],
    "miscellaneousLabel": null
  },
  {
    "item": "CM361",
    "category": "Casing",
    "categorySlug": "casing",
    "dimensions": "11/16\" x 3-1/4\"",
    "thickness": 0.6875,
    "width": 3.25,
    "configs": [
      "12 FT",
      "6/0",
      "5/0",
      "4/0",
      "3/0",
      "2/6",
      "2/0"
    ],
    "miscellaneousLabel": null
  },
  {
    "item": "CM366",
    "category": "Casing",
    "categorySlug": "casing",
    "dimensions": "11/16\" x 2-1/4\"",
    "thickness": 0.6875,
    "width": 2.25,
    "configs": [
      "12 FT",
      "8 FT",
      "6/0",
      "5/0",
      "4/0",
      "3/0",
      "2/6",
      "2/0"
    ],
    "miscellaneousLabel": null
  },
  {
    "item": "CM371",
    "category": "Casing",
    "categorySlug": "casing",
    "dimensions": "11/16\" x 3\"",
    "thickness": 0.6875,
    "width": 3,
    "configs": [
      "12 FT",
      "6/0",
      "5/0",
      "4/0",
      "3/0",
      "2/6",
      "2/0"
    ],
    "miscellaneousLabel": null
  },
  {
    "item": "CM376",
    "category": "Casing",
    "categorySlug": "casing",
    "dimensions": "11/16\" x 2-1/4\"",
    "thickness": 0.6875,
    "width": 2.25,
    "configs": [
      "12 FT",
      "8 FT",
      "6/0",
      "5/0",
      "4/0",
      "3/0",
      "2/6",
      "2/0"
    ],
    "miscellaneousLabel": null
  },
  {
    "item": "CM442",
    "category": "Casing",
    "categorySlug": "casing",
    "dimensions": "11/16\" x 2-1/4\"",
    "thickness": 0.6875,
    "width": 2.25,
    "configs": [
      "12 FT",
      "6/0",
      "5/0",
      "4/0",
      "3/0",
      "2/6",
      "2/0"
    ],
    "miscellaneousLabel": null
  },
  {
    "item": "CM444",
    "category": "Casing",
    "categorySlug": "casing",
    "dimensions": "11/16\" x 3-1/4\"",
    "thickness": 0.6875,
    "width": 3.25,
    "configs": [
      "12 FT",
      "8 FT",
      "6/0",
      "5/0",
      "4/0",
      "3/0",
      "2/6",
      "2/0"
    ],
    "miscellaneousLabel": null
  },
  {
    "item": "CM445",
    "category": "Casing",
    "categorySlug": "casing",
    "dimensions": "11/16\" x 3-1/4\"",
    "thickness": 0.6875,
    "width": 3.25,
    "configs": [
      "12 FT",
      "8 FT",
      "6/0",
      "5/0",
      "4/0",
      "3/0",
      "2/6",
      "2/0",
      "12 FT x 48 IN R",
      "8 FT x 48 IN R",
      "7 FT x 84 IN",
      "7 FT x 48 IN",
      "4.5 FT x 30 IN R"
    ],
    "miscellaneousLabel": null
  },
  {
    "item": "CM470",
    "category": "Casing",
    "categorySlug": "casing",
    "dimensions": "1-1/16\" x 3-1/16\"",
    "thickness": 1.0625,
    "width": 3.0625,
    "configs": [
      "12 FT",
      "6/0",
      "5/0",
      "4/0",
      "3/0",
      "2/6",
      "2/0"
    ],
    "miscellaneousLabel": null
  },
  {
    "item": "CM610",
    "category": "Base",
    "categorySlug": "base",
    "dimensions": "9/16\" x 5-1/4\"",
    "thickness": 0.5625,
    "width": 5.25,
    "configs": [
      "12 FT"
    ],
    "miscellaneousLabel": null
  },
  {
    "item": "CM616",
    "category": "Base",
    "categorySlug": "base",
    "dimensions": "11/16\" x 6-1/8\"",
    "thickness": 0.6875,
    "width": 6.125,
    "configs": [
      "12 FT"
    ],
    "miscellaneousLabel": null
  },
  {
    "item": "CM618",
    "category": "Base",
    "categorySlug": "base",
    "dimensions": "9/16\" x 5-1/4\"",
    "thickness": 0.5625,
    "width": 5.25,
    "configs": [
      "12 FT"
    ],
    "miscellaneousLabel": null
  },
  {
    "item": "CM623",
    "category": "Base",
    "categorySlug": "base",
    "dimensions": "9/16\" x 3-1/4\"",
    "thickness": 0.5625,
    "width": 3.25,
    "configs": [
      "12 FT"
    ],
    "miscellaneousLabel": null
  },
  {
    "item": "CM663",
    "category": "Base",
    "categorySlug": "base",
    "dimensions": "9/16\" x 3-1/4\"",
    "thickness": 0.5625,
    "width": 3.25,
    "configs": [
      "12 FT"
    ],
    "miscellaneousLabel": null
  },
  {
    "item": "CM753",
    "category": "Base",
    "categorySlug": "base",
    "dimensions": "9/16\" x 3-1/4\"",
    "thickness": 0.5625,
    "width": 3.25,
    "configs": [
      "12 FT"
    ],
    "miscellaneousLabel": null
  },
  {
    "item": "CM809",
    "category": "Back Band",
    "categorySlug": "back-band",
    "dimensions": "1-3/8\" x 1-5/8\" x 1\" Rab",
    "thickness": 1.375,
    "width": 1.625,
    "configs": [
      "12 FT"
    ],
    "miscellaneousLabel": null
  },
  {
    "item": "CM937",
    "category": "Stop",
    "categorySlug": "stop",
    "dimensions": "3/8\" x 1-1/4\"",
    "thickness": 0.375,
    "width": 1.25,
    "configs": [
      "12 FT"
    ],
    "miscellaneousLabel": null
  },
  {
    "item": "CM940",
    "category": "Stop",
    "categorySlug": "stop",
    "dimensions": "7/16\" x 7/8\"",
    "thickness": 0.4375,
    "width": 0.875,
    "configs": [
      "12 FT"
    ],
    "miscellaneousLabel": null
  },
  {
    "item": "CM956 CRB",
    "category": "Miscellaneous",
    "categorySlug": "miscellaneous",
    "dimensions": "7/16\" x 4-1/4\"",
    "thickness": 0.4375,
    "width": 4.25,
    "configs": [
      "12 FT"
    ],
    "miscellaneousLabel": "Chair Rail Backer"
  },
  {
    "item": "PM5",
    "category": "Panel Mould",
    "categorySlug": "panel-mould",
    "dimensions": "11/16\" x 1-1/8\"",
    "thickness": 0.6875,
    "width": 1.125,
    "configs": [
      "12 FT"
    ],
    "miscellaneousLabel": null
  }
];

/** Main image path for each item (under /stock-items/). */
export const STOCK_ITEM_IMAGES: Record<string, string> = {
  "1 IN QTR": "/stock-items/1 IN QTR/1 IN QTR.jpg",
  "C136": "/stock-items/C136/C136.jpg",
  "C281": "/stock-items/C281/C281.jpg",
  "C42": "/stock-items/C42/C42.jpg",
  "CM1": "/stock-items/CM1/CM1.jpg",
  "CM100": "/stock-items/CM100/CM100.jpg",
  "CM101": "/stock-items/CM101/CM101.jpg",
  "CM105": "/stock-items/CM105/CM105.jpg",
  "CM106": "/stock-items/CM106/CM106.jpg",
  "CM126": "/stock-items/CM126/CM126.jpg",
  "CM127": "/stock-items/CM127/CM127.jpg",
  "CM131": "/stock-items/CM131/CM131.jpg",
  "CM137": "/stock-items/CM137/CM137.jpg",
  "CM163": "/stock-items/CM163/CM163.jpg",
  "CM164": "/stock-items/CM164/CM164.jpg",
  "CM166": "/stock-items/CM166/CM166.jpg",
  "CM167": "/stock-items/CM167/CM167.jpg",
  "CM180": "/stock-items/CM180/CM180.jpg",
  "CM183": "/stock-items/CM183/CM183.jpg",
  "CM184": "/stock-items/CM184/CM184.jpg",
  "CM197": "/stock-items/CM197/CM197.jpg",
  "CM2": "/stock-items/CM2/CM2.jpg",
  "CM205": "/stock-items/CM205/CM205.jpg",
  "CM210": "/stock-items/CM210/CM210.jpg",
  "CM273": "/stock-items/CM273/CM273.jpg",
  "CM28": "/stock-items/CM28/CM28.jpg",
  "CM280": "/stock-items/CM280/CM280.jpg",
  "CM281": "/stock-items/CM281/CM281.jpg",
  "CM297": "/stock-items/CM297/CM297.jpg",
  "CM300": "/stock-items/CM300/CM300.jpg",
  "CM302": "/stock-items/CM302/CM302.jpg",
  "CM356": "/stock-items/CM356/CM356.jpg",
  "CM361": "/stock-items/CM361/CM361.jpg",
  "CM366": "/stock-items/CM366/CM366.jpg",
  "CM37": "/stock-items/CM37/CM37.jpg",
  "CM371": "/stock-items/CM371/CM371.jpg",
  "CM376": "/stock-items/CM376/CM376.jpg",
  "CM442": "/stock-items/CM442/CM442.jpg",
  "CM444": "/stock-items/CM444/CM444.jpg",
  "CM445": "/stock-items/CM445/CM445.jpg",
  "CM45": "/stock-items/CM45/CM45.jpg",
  "CM47": "/stock-items/CM47/CM47.jpg",
  "CM470": "/stock-items/CM470/CM470.jpg",
  "CM49": "/stock-items/CM49/CM49.jpg",
  "CM52": "/stock-items/CM52/CM52.jpg",
  "CM610": "/stock-items/CM610/CM610.jpg",
  "CM616": "/stock-items/CM616/CM616.jpg",
  "CM618": "/stock-items/CM618/CM618.jpg",
  "CM623": "/stock-items/CM623/CM623.jpg",
  "CM663": "/stock-items/CM663/CM663.jpg",
  "CM75": "/stock-items/CM75/CM75.jpg",
  "CM753": "/stock-items/CM753/CM753.jpg",
  "CM809": "/stock-items/CM809/CM809.jpg",
  "CM93": "/stock-items/CM93/CM93.jpg",
  "CM937": "/stock-items/CM937/CM937.jpg",
  "CM940": "/stock-items/CM940/CM940.jpg",
  "CM956 CRB": "/stock-items/CM956 CRB/CM956 CRB.jpg",
  "PM5": "/stock-items/PM5/PM5.jpg"
};

/** Per-item, per-config-folder (e.g. "20" for 2/0) assets: images and optional .glb. */
export const STOCK_ITEM_CONFIG_ASSETS: Record<string, Record<string, { images: string[]; glb: string | null }>> = {
  "1 IN QTR": {},
  "C136": {},
  "C281": {},
  "C42": {},
  "CM1": {},
  "CM100": {},
  "CM101": {},
  "CM105": {},
  "CM106": {},
  "CM126": {},
  "CM127": {},
  "CM131": {},
  "CM137": {},
  "CM163": {},
  "CM164": {},
  "CM166": {},
  "CM167": {},
  "CM180": {
    "20": {
      "images": [
        "CM180-20-1.PNG",
        "CM180-20-2.png"
      ],
      "glb": "CM180-20.glb"
    }
  },
  "CM183": {},
  "CM184": {},
  "CM197": {},
  "CM2": {},
  "CM205": {},
  "CM210": {},
  "CM273": {},
  "CM28": {},
  "CM280": {},
  "CM281": {},
  "CM297": {},
  "CM300": {},
  "CM302": {},
  "CM356": {},
  "CM361": {},
  "CM366": {},
  "CM37": {},
  "CM371": {},
  "CM376": {},
  "CM442": {},
  "CM444": {},
  "CM445": {},
  "CM45": {},
  "CM47": {},
  "CM470": {},
  "CM49": {},
  "CM52": {},
  "CM610": {},
  "CM616": {},
  "CM618": {},
  "CM623": {},
  "CM663": {},
  "CM75": {},
  "CM753": {},
  "CM809": {},
  "CM93": {},
  "CM937": {},
  "CM940": {},
  "CM956 CRB": {},
  "PM5": {}
};

export function getStockItemByModel(model: string): StockItem | undefined {
  return STOCK_ITEMS.find((i) => i.item.toUpperCase() === model.toUpperCase());
}

export function getStockItemsByCategory(categorySlug: string): StockItem[] {
  return STOCK_ITEMS.filter((i) => i.categorySlug === categorySlug);
}
